[package]
name = "kclvm-ast-pretty"
version = "0.4.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kclvm-parser = {path = "../parser", version = "0.4.5"}
kclvm-error = {path = "../error", version = "0.4.5"}
kclvm-ast = {path = "../ast", version = "0.4.5"}

indexmap = "1.0"
fancy-regex = "0.7.1"
pretty_assertions = "1.3.0"
compiler_base_session = {path = "../../compiler_base/session", version = "0.0.12"}
compiler_base_macros = "0.0.1"
