[package]
name = "compiler_base_span"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc_span = {path="../3rdparty/rustc_span", version="0.0.0"}
