[package]
name = "kclvm-runner"
version = "0.4.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0"

[dependencies]
serde_json = "1.0"
serde = { version = "1", features = ["derive"] }
glob = "0.3.0"
walkdir = "2"
libc = "0.2.112"
indexmap = "1.0"
fslock = "0.2.1"
libloading = "0.7.3"
threadpool = "1.0"
chrono = "0.4.19"
tempfile = "3.3.0"
anyhow = "1.0"
once_cell = "1.10"
cc = "1.0"
compiler_base_session = {path = "../../compiler_base/session", version = "0.0.12"}
compiler_base_macros = "0.0.1"

kclvm-ast = {path = "../ast", version = "0.4.5"}
kclvm-parser = {path = "../parser", version = "0.4.5"}
kclvm-compiler = {path = "../compiler", version = "0.4.5"}
kclvm-config = {path = "../config", version = "0.4.5"}
kclvm-runtime = {path = "../runtime", version = "0.4.5"}
kclvm-sema = {path = "../sema", version = "0.4.5"}
kclvm-version = {path = "../version", version = "0.4.5"}
kclvm-error = {path = "../error", version="0.4.5"}
kclvm-query = {path = "../query", version="0.4.5"}
kclvm-utils = {path = "../utils", version="0.4.5"}

[dev-dependencies]
kclvm-parser = {path = "../parser", version = "0.4.5"}
criterion = "0.3"

[[bench]]
name = "bench_runner"
harness = false