name: release
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  test:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: "true"

      # Prerequisite

      - name: Install Python3 and LLVM
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget curl make
          sudo apt-get install python3 python3-pip -y
          sudo apt-get install -y clang-12 lld-12
          sudo ln -sf /usr/bin/clang-12 /usr/bin/clang
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.67
          override: true
          components: clippy, rustfmt

      # KCLVM build

      - name: Build KCLVM
        run: export PATH=$PATH:$PWD/_build/dist/ubuntu/kclvm/bin && make build
        shell: bash

      # KCLVM docker image build and upload

      - name: Copy Dockerfile to the current work directory
        run: cp scripts/docker/kclvm/Dockerfile .
        shell: bash
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: kusionstack/kclvm
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
