name: build-and-test-ubuntu
on: ["push", "pull_request"]
jobs:
  build-and-test:
    # Ref: https://github.com/actions/runner-images/tree/main/images/linux
    name: Test
    runs-on: ubuntu-latest
    container:
      image: kcllang/kcl-builder
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Delete rust cargo
        run: rm -rf /root/.cargo/bin
        shell: bash
      - name: Install rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.67
          override: true
          components: clippy, rustfmt
      - name: Code format check
        working-directory: ./kclvm
        run: cargo fmt --check
        shell: bash
      - name: Code clippy check
        working-directory: ./kclvm
        run: cargo clippy --no-deps -r
        shell: bash
      - name: Grammar test
        working-directory: ./kclvm
        run: export PATH=$PATH:$PWD/../_build/dist/ubuntu/kclvm/bin && make install-rustc-wasm && make && make test-grammar
        shell: bash
      - name: Runtime test
        working-directory: ./kclvm
        run: export PATH=$PATH:$PWD/../_build/dist/ubuntu/kclvm/bin && make install-rustc-wasm && make && make test-runtime
        shell: bash
      - name: Install kpm
        run: go install kcl-lang.io/kpm@latest

      - name: Unit test
        working-directory: ./kclvm
        run: export PATH=$PATH:$PWD/../_build/dist/ubuntu/kclvm/bin && make install-rustc-wasm && make && make codecov-lcov
        shell: bash
      - name: Konfig test
        working-directory: ./kclvm
        run: export PATH=$PATH:$PWD/../_build/dist/ubuntu/kclvm/bin && make install-rustc-wasm && make && make test-konfig
        shell: bash
      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./kclvm/.kclvm/lcov.info

      - uses: actions/upload-artifact@v3
        with:
          name: kcl-linux-amd64
          path: _build/dist/ubuntu/kclvm
