name: build-and-test-windows
on: ["push", "pull_request"]
jobs:
  build-and-test:
    runs-on: windows-2019
    env:
      LLVM_SYS_120_PREFIX: "C:/LLVM"
      KCLVM_CLANG: "C:/LLVM/bin/clang.exe"
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
         submodules: 'true'

      - run: clang --version
      - run: cargo --version

      - run: Rename-Item "C:/Program Files/LLVM" "C:/Program Files/LLVM-old"

      # Install LLVM-12
      - run: Invoke-WebRequest -Uri https://github.com/KusionStack/llvm-package-windows/releases/download/v12.0.1/LLVM-12.0.1-win64.7z -OutFile C:/LLVM-12.0.1-win64.7z
      - run: Get-FileHash -Algorithm MD5 C:/LLVM-12.0.1-win64.7z # md5: 3fcf77f82c6c3ee650711439b20aebe5
      - run: 7z x -y C:/LLVM-12.0.1-win64.7z -o"C:/LLVM"
      - run: Remove-Item C:/LLVM-12.0.1-win64.7z

      - run: echo "C:/LLVM/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Run make
        working-directory: scripts/build-windows
        run: mingw32-make

      - run: scripts/build-windows/_output/kclvm-windows/kclvm_cli.exe -h
      - run: scripts/build-windows/_output/kclvm-windows/kcl.exe ./samples/hello.k

      - run: Compress-Archive -Path scripts/build-windows/_output/kclvm-windows -DestinationPath C:/kclvm-windows.zip
      - run: Get-FileHash -Algorithm MD5 C:/kclvm-windows.zip
