[package]
name = "kclvm-query"
version = "0.4.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
compiler_base_session = {path = "../../compiler_base/session", version = "0.0.12"}
compiler_base_macros = "0.0.1"

kclvm-ast = {path = "../ast", version = "0.4.5"}
kclvm-ast-pretty = {path = "../ast_pretty", version = "0.4.5"}
kclvm-parser = {path = "../parser", version = "0.4.5"}
kclvm-sema = {path = "../sema", version = "0.4.5"}
kclvm-error = {path = "../error", version = "0.4.5"}

[dev-dependencies]
pretty_assertions = "1.2.1"
