[package]
name = "kclvm-query"
version = "0.4.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
compiler_base_session = {path = "../../compiler_base/session"}
compiler_base_macros = "0.0.1"
indexmap = "1.0"

kclvm-ast = {path = "../ast"}
kclvm-ast-pretty = {path = "../ast_pretty"}
kclvm-parser = {path = "../parser"}
kclvm-sema = {path = "../sema"}
kclvm-error = {path = "../error"}

[dev-dependencies]
pretty_assertions = "1.2.1"
