[package]
name = "kclvm-sema"
version = "0.4.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.9", features = ["macros"] }
ahash = "0.7.2"
indexmap = "1.0"
bit-set = "0.5.0"
bitflags = "1.2.1"
once_cell = "1.5.2"
fancy-regex = "0.7.1"
unicode_names2 = "0.4"
petgraph = "0.6.0"
anyhow = "1.0"
regex = "1.7.0"
kclvm-ast = {path = "../ast"}
kclvm-runtime = {path = "../runtime"}
kclvm-error = {path = "../error"}
kclvm-span = {path = "../span"}
compiler_base_span = {path = "../../compiler_base/span", version = "0.0.2"}
compiler_base_session = {path = "../../compiler_base/session"}
compiler_base_macros = "0.0.1"
compiler_base_error = "0.0.8"

[dev-dependencies]
kclvm-parser = {path = "../parser"}
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false

